query:
  description: "Query the Argos Translate service and optionally return results."
  fields:
    query:
      required: true
      description: "The query string to send."
      example: "search term"
      selector:
        text:
  response:
    optional: true
