translate:
  fields:
    text:
      required: true
      example: "Hello, how are you?"
      selector:
        text:
          multiline: true
    source:
      required: true
      example: "en"
      selector:
        text:
    target:
      required: true
      example: "es"
      selector:
        text:
